# Generated by Django 5.2.7 on 2026-05-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('Pending', 'در انتظار'), ('InProgress', 'در حال انجام'), ('Done', 'انجام شد')], default='Pending', max_length=10, verbose_name='وضعیت کار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
